version: '3'

services:
  php-app:
    build:
      context: .
      dockerfile: docker/php82/Dockerfile
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    depends_on:
      - sqlite-container

  sqlite-container:
    image: sqlite
    volumes:
      - ./personal_finance:/data
